export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const CREATE_PROJECT_BEGIN = 'CREATE_PROJECT_BEGIN';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR';

export const GET_PROJECTS_BEGIN = 'GET_PROJECTS_BEGIN';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';

export const SET_EDIT_PROJECT = 'SET_EDIT_PROJECT';

export const DELETE_PROJECT_BEGIN = 'DELETE_PROJECT_BEGIN';
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR';

export const EDIT_PROJECT_BEGIN = 'EDIT_PROJECT_BEGIN';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';
export const EDIT_PROJECT_ERROR = 'EDIT_PROJECT_ERROR';
